apiVersion: v1
kind: Service
metadata:
  name: {{ include "api-backend.componentName" (dict "root" $ "component" "backend") }}
  labels:
    {{- include "api-backend.labels" (dict "root" $ "component" "backend") | nindent 4 }}
spec:
  type: ClusterIP
  ports:
    - name: http
      port: {{ .Values.backend.service.port }}
      targetPort: http
  selector:
    {{- include "api-backend.selectorLabels" (dict "root" $ "component" "backend") | nindent 4 }}
